const express = require('express');
const app = express();

//MYLOGGER IS A MIDDLEWARE FUNCTION.  SIMPLE FUNCTION
//USED TO INSERT THE MIDDLEWARE FUNCTION FIRST THEN 
//GET THE REQUEST AND RESPONSE OBJECTS.  NEXT GOES TO 
//THE NEXT MIDDLEWARE FUNCTION.
const myLogger = (request, response, next) => {
  console.log('LOGGED');
  next();
  //NEXT IS OPTIONAL.  IF NEXT IS REPLACED WITH RESPONSE.SEND, 
  //THE ROUTE WILL NEVER GET TO APP.GET RESPONSE.  
};

//TELLS EXPRESS APP TO USE THIS FUNCTION BETWEEN EVERY REQUEST
// AND RESPONSE
app.use(myLogger);

app.get('/', function (request, response) {
  response.send('Hello World!');
});
//IN BROWSER, 'HELLO WORLD!' PRINTS, IN CONSOLE, LOGGED PRINTS. EVERY
//REFRESH WILL PRINT LOGGED AGAIN AND AGAIN.  THERE CAN BE MORE THAN 
//ONE MIDDLEWARE FUNCTIONS.  EACH FUNCTION GETS APP.USE(NAMEOFFUNCTION).
//EACH MIDDLEWARE FUNCTION CAN SEND EITHER A RESPONSE OR INVOKE NEXT();


app.listen(8000);


